// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#ifndef _TEST_UI_H
#define _TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_home1.h"
#include "ui_Children1.h"
#include "ui_chicken1.h"
#include "ui_InHome1.h"
#include "ui_seting.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_backgraund_png);    // assets/backgraund.png
LV_IMG_DECLARE(ui_img_1766029311);    // assets/button_домой_цветная.png
LV_IMG_DECLARE(ui_img_2030772891);    // assets/button_дети_цветная.png
LV_IMG_DECLARE(ui_img_1962788573);    // assets/button_курятник_цветная.png
LV_IMG_DECLARE(ui_img_86013472);    // assets/button_дом_цветная.png
LV_IMG_DECLARE(ui_img_105946131);    // assets/button_Настройки_цветная.png
LV_IMG_DECLARE(ui_img_light_chicken_png);    // assets/light_chicken.png
LV_IMG_DECLARE(ui_img_light_chicken_off_png);    // assets/light_chicken_off.png
LV_IMG_DECLARE(ui_img_open_color_png);    // assets/open_color.png
LV_IMG_DECLARE(ui_img_open_color_off_png);    // assets/open_color_off.png
LV_IMG_DECLARE(ui_img_close_color_png);    // assets/close_color.png
LV_IMG_DECLARE(ui_img_close_color_off_png);    // assets/close_color_off.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
