// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#include "ui.h"

lv_obj_t * uic_Button12;
lv_obj_t * ui_Children1 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Button12 = NULL;
// event funtions
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_home1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home1_screen_init);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_chicken1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_chicken1_screen_init);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InHome1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InHome1_screen_init);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_seting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_seting_screen_init);
    }
}

// build funtions

void ui_Children1_screen_init(void)
{
    ui_Children1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Children1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Children1, &ui_img_backgraund_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_button_create(ui_Children1);
    lv_obj_set_width(ui_Button7, 122);
    lv_obj_set_height(ui_Button7, 155);
    lv_obj_set_x(ui_Button7, -579);
    lv_obj_set_y(ui_Button7, -323);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button7, &ui_img_1766029311, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_button_create(ui_Children1);
    lv_obj_set_width(ui_Button6, 122);
    lv_obj_set_height(ui_Button6, 155);
    lv_obj_set_x(ui_Button6, -579);
    lv_obj_set_y(ui_Button6, -162);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button6, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button6, &ui_img_2030772891, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_button_create(ui_Children1);
    lv_obj_set_width(ui_Button10, 122);
    lv_obj_set_height(ui_Button10, 155);
    lv_obj_set_x(ui_Button10, -579);
    lv_obj_set_y(ui_Button10, 10);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button10, &ui_img_1962788573, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_button_create(ui_Children1);
    lv_obj_set_width(ui_Button11, 122);
    lv_obj_set_height(ui_Button11, 155);
    lv_obj_set_x(ui_Button11, -579);
    lv_obj_set_y(ui_Button11, 178);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button11, &ui_img_86013472, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_button_create(ui_Children1);
    lv_obj_set_width(ui_Button12, 122);
    lv_obj_set_height(ui_Button12, 132);
    lv_obj_set_x(ui_Button12, -579);
    lv_obj_set_y(ui_Button12, 333);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button12, &ui_img_105946131, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    uic_Button12 = ui_Button12;

}

void ui_Children1_screen_destroy(void)
{
    if(ui_Children1) lv_obj_del(ui_Children1);

    // NULL screen variables
    ui_Children1 = NULL;
    ui_Button7 = NULL;
    ui_Button6 = NULL;
    ui_Button10 = NULL;
    ui_Button11 = NULL;
    uic_Button12 = NULL;
    ui_Button12 = NULL;

}
