// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#include "ui.h"

lv_obj_t * uic_ChickenThermostateAutomation;
lv_obj_t * uic_ImgButton3;
lv_obj_t * uic_chicken1;
lv_obj_t * ui_chicken1 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Button13 = NULL;
lv_obj_t * ui_Button14 = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_ChickenThermostateAutomation = NULL;
// event funtions
void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_home1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home1_screen_init);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Children1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Children1_screen_init);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InHome1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InHome1_screen_init);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_seting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_seting_screen_init);
    }
}

// build funtions

void ui_chicken1_screen_init(void)
{
    ui_chicken1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_chicken1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_chicken1, &ui_img_backgraund_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_button_create(ui_chicken1);
    lv_obj_set_width(ui_Button9, 122);
    lv_obj_set_height(ui_Button9, 155);
    lv_obj_set_x(ui_Button9, -579);
    lv_obj_set_y(ui_Button9, -323);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button9, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button9, &ui_img_1766029311, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_button_create(ui_chicken1);
    lv_obj_set_width(ui_Button13, 122);
    lv_obj_set_height(ui_Button13, 155);
    lv_obj_set_x(ui_Button13, -579);
    lv_obj_set_y(ui_Button13, -162);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button13, &ui_img_2030772891, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_button_create(ui_chicken1);
    lv_obj_set_width(ui_Button14, 122);
    lv_obj_set_height(ui_Button14, 155);
    lv_obj_set_x(ui_Button14, -579);
    lv_obj_set_y(ui_Button14, 10);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button14, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button14, &ui_img_1962788573, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_button_create(ui_chicken1);
    lv_obj_set_width(ui_Button15, 122);
    lv_obj_set_height(ui_Button15, 155);
    lv_obj_set_x(ui_Button15, -579);
    lv_obj_set_y(ui_Button15, 178);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button15, &ui_img_86013472, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_button_create(ui_chicken1);
    lv_obj_set_width(ui_Button16, 122);
    lv_obj_set_height(ui_Button16, 132);
    lv_obj_set_x(ui_Button16, -579);
    lv_obj_set_y(ui_Button16, 333);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button16, &ui_img_105946131, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imagebutton_create(ui_chicken1);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_light_chicken_png, NULL);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui_img_light_chicken_off_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 150);
    lv_obj_set_height(ui_ImgButton2, 179);
    lv_obj_set_x(ui_ImgButton2, 556);
    lv_obj_set_y(ui_ImgButton2, 36);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_ImgButton3 = lv_imagebutton_create(ui_chicken1);
    lv_imagebutton_set_src(ui_ImgButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_open_color_png, NULL);
    lv_imagebutton_set_src(ui_ImgButton3, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui_img_open_color_off_png, NULL);
    lv_obj_set_width(ui_ImgButton3, 150);
    lv_obj_set_height(ui_ImgButton3, 179);
    lv_obj_set_x(ui_ImgButton3, 556);
    lv_obj_set_y(ui_ImgButton3, -218);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_ImgButton4 = lv_imagebutton_create(ui_chicken1);
    lv_imagebutton_set_src(ui_ImgButton4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_close_color_png, NULL);
    lv_imagebutton_set_src(ui_ImgButton4, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui_img_close_color_off_png, NULL);
    lv_obj_set_width(ui_ImgButton4, 150);
    lv_obj_set_height(ui_ImgButton4, 179);
    lv_obj_set_x(ui_ImgButton4, 556);
    lv_obj_set_y(ui_ImgButton4, 290);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ImgButton4, LV_STATE_DISABLED);       /// States

    ui_ChickenThermostateAutomation = lv_switch_create(ui_chicken1);
    lv_obj_set_width(ui_ChickenThermostateAutomation, 100);
    lv_obj_set_height(ui_ChickenThermostateAutomation, 50);
    lv_obj_set_x(ui_ChickenThermostateAutomation, -413);
    lv_obj_set_y(ui_ChickenThermostateAutomation, -250);
    lv_obj_set_align(ui_ChickenThermostateAutomation, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    uic_chicken1 = ui_chicken1;
    uic_ImgButton3 = ui_ImgButton3;
    uic_ChickenThermostateAutomation = ui_ChickenThermostateAutomation;

}

void ui_chicken1_screen_destroy(void)
{
    if(ui_chicken1) lv_obj_del(ui_chicken1);

    // NULL screen variables
    uic_chicken1 = NULL;
    ui_chicken1 = NULL;
    ui_Button9 = NULL;
    ui_Button13 = NULL;
    ui_Button14 = NULL;
    ui_Button15 = NULL;
    ui_Button16 = NULL;
    ui_ImgButton2 = NULL;
    uic_ImgButton3 = NULL;
    ui_ImgButton3 = NULL;
    ui_ImgButton4 = NULL;
    uic_ChickenThermostateAutomation = NULL;
    ui_ChickenThermostateAutomation = NULL;

}
