// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#ifndef UI_CHILDREN1_H
#define UI_CHILDREN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Children1
extern void ui_Children1_screen_init(void);
extern void ui_Children1_screen_destroy(void);
extern lv_obj_t * ui_Children1;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Button6;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Button12;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

