// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#include "ui.h"

// COMPONENT teplica

lv_obj_t * ui_teplica_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_teplica;
    cui_teplica = lv_button_create(comp_parent);
    lv_obj_set_width(cui_teplica, 100);
    lv_obj_set_height(cui_teplica, 50);
    lv_obj_set_align(cui_teplica, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_teplica, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_teplica, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_TEPLICA_NUM);
    children[UI_COMP_TEPLICA_TEPLICA] = cui_teplica;
    lv_obj_add_event_cb(cui_teplica, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_teplica, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_teplica_create_hook(cui_teplica);
    return cui_teplica;
}

