// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#ifndef _UI_COMP_TEPLICA_H
#define _UI_COMP_TEPLICA_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT teplica
#define UI_COMP_TEPLICA_TEPLICA 0
#define _UI_COMP_TEPLICA_NUM 1
lv_obj_t * ui_teplica_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
