// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#ifndef UI_CHICKEN1_H
#define UI_CHICKEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_chicken1
extern void ui_chicken1_screen_init(void);
extern void ui_chicken1_screen_destroy(void);
extern lv_obj_t * ui_chicken1;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Button14;
extern void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_ChickenThermostateAutomation;
// CUSTOM VARIABLES
extern lv_obj_t * uic_chicken1;
extern lv_obj_t * uic_ImgButton3;
extern lv_obj_t * uic_ChickenThermostateAutomation;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

