// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#include "ui.h"

void ui_comp_teplica_create_hook(lv_obj_t * comp)
{
}
