// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#include "ui.h"

lv_obj_t * uic_Button5;
lv_obj_t * uic_Button4;
lv_obj_t * uic_Button3;
lv_obj_t * uic_Button2;
lv_obj_t * uic_Button1;
lv_obj_t * uic_home1;
lv_obj_t * ui_home1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Button5 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Children1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Children1_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_chicken1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_chicken1_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InHome1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InHome1_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_seting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_seting_screen_init);
    }
}

// build funtions

void ui_home1_screen_init(void)
{
    ui_home1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_home1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_home1, &ui_img_backgraund_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_home1);
    lv_obj_set_width(ui_Button1, 122);
    lv_obj_set_height(ui_Button1, 155);
    lv_obj_set_x(ui_Button1, -579);
    lv_obj_set_y(ui_Button1, -323);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button1, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button1, &ui_img_1766029311, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_home1);
    lv_obj_set_width(ui_Button2, 122);
    lv_obj_set_height(ui_Button2, 155);
    lv_obj_set_x(ui_Button2, -579);
    lv_obj_set_y(ui_Button2, -162);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button2, &ui_img_2030772891, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_home1);
    lv_obj_set_width(ui_Button3, 122);
    lv_obj_set_height(ui_Button3, 155);
    lv_obj_set_x(ui_Button3, -579);
    lv_obj_set_y(ui_Button3, 10);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button3, &ui_img_1962788573, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_home1);
    lv_obj_set_width(ui_Button4, 122);
    lv_obj_set_height(ui_Button4, 155);
    lv_obj_set_x(ui_Button4, -579);
    lv_obj_set_y(ui_Button4, 178);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button4, &ui_img_86013472, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_home1);
    lv_obj_set_width(ui_Button5, 122);
    lv_obj_set_height(ui_Button5, 132);
    lv_obj_set_x(ui_Button5, -579);
    lv_obj_set_y(ui_Button5, 333);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button5, &ui_img_105946131, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    uic_home1 = ui_home1;
    uic_Button1 = ui_Button1;
    uic_Button2 = ui_Button2;
    uic_Button3 = ui_Button3;
    uic_Button4 = ui_Button4;
    uic_Button5 = ui_Button5;

}

void ui_home1_screen_destroy(void)
{
    if(ui_home1) lv_obj_del(ui_home1);

    // NULL screen variables
    uic_home1 = NULL;
    ui_home1 = NULL;
    uic_Button1 = NULL;
    ui_Button1 = NULL;
    uic_Button2 = NULL;
    ui_Button2 = NULL;
    uic_Button3 = NULL;
    ui_Button3 = NULL;
    uic_Button4 = NULL;
    ui_Button4 = NULL;
    uic_Button5 = NULL;
    ui_Button5 = NULL;

}
