// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#ifndef UI_HOME1_H
#define UI_HOME1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home1
extern void ui_home1_screen_init(void);
extern void ui_home1_screen_destroy(void);
extern lv_obj_t * ui_home1;
extern lv_obj_t * ui_Button1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_home1;
extern lv_obj_t * uic_Button1;
extern lv_obj_t * uic_Button2;
extern lv_obj_t * uic_Button3;
extern lv_obj_t * uic_Button4;
extern lv_obj_t * uic_Button5;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

