// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#include "ui.h"

lv_obj_t * uic_InHome1;
lv_obj_t * ui_InHome1 = NULL;
lv_obj_t * ui_Button17 = NULL;
lv_obj_t * ui_Button18 = NULL;
lv_obj_t * ui_Button19 = NULL;
lv_obj_t * ui_Button20 = NULL;
lv_obj_t * ui_Button21 = NULL;
// event funtions
void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_home1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home1_screen_init);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Children1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Children1_screen_init);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_chicken1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_chicken1_screen_init);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_seting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_seting_screen_init);
    }
}

// build funtions

void ui_InHome1_screen_init(void)
{
    ui_InHome1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_InHome1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_InHome1, &ui_img_backgraund_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_button_create(ui_InHome1);
    lv_obj_set_width(ui_Button17, 122);
    lv_obj_set_height(ui_Button17, 155);
    lv_obj_set_x(ui_Button17, -579);
    lv_obj_set_y(ui_Button17, -323);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button17, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button17, &ui_img_1766029311, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button18 = lv_button_create(ui_InHome1);
    lv_obj_set_width(ui_Button18, 122);
    lv_obj_set_height(ui_Button18, 155);
    lv_obj_set_x(ui_Button18, -579);
    lv_obj_set_y(ui_Button18, -162);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button18, &ui_img_2030772891, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_button_create(ui_InHome1);
    lv_obj_set_width(ui_Button19, 122);
    lv_obj_set_height(ui_Button19, 155);
    lv_obj_set_x(ui_Button19, -579);
    lv_obj_set_y(ui_Button19, 10);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button19, &ui_img_1962788573, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button20 = lv_button_create(ui_InHome1);
    lv_obj_set_width(ui_Button20, 122);
    lv_obj_set_height(ui_Button20, 155);
    lv_obj_set_x(ui_Button20, -579);
    lv_obj_set_y(ui_Button20, 178);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button20, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button20, &ui_img_86013472, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button21 = lv_button_create(ui_InHome1);
    lv_obj_set_width(ui_Button21, 122);
    lv_obj_set_height(ui_Button21, 132);
    lv_obj_set_x(ui_Button21, -579);
    lv_obj_set_y(ui_Button21, 333);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button21, &ui_img_105946131, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    uic_InHome1 = ui_InHome1;

}

void ui_InHome1_screen_destroy(void)
{
    if(ui_InHome1) lv_obj_del(ui_InHome1);

    // NULL screen variables
    uic_InHome1 = NULL;
    ui_InHome1 = NULL;
    ui_Button17 = NULL;
    ui_Button18 = NULL;
    ui_Button19 = NULL;
    ui_Button20 = NULL;
    ui_Button21 = NULL;

}
