// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#ifndef UI_INHOME1_H
#define UI_INHOME1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InHome1
extern void ui_InHome1_screen_init(void);
extern void ui_InHome1_screen_destroy(void);
extern lv_obj_t * ui_InHome1;
extern void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Button20;
extern void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
// CUSTOM VARIABLES
extern lv_obj_t * uic_InHome1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

