// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#include "ui.h"

lv_obj_t * uic_seting;
lv_obj_t * ui_seting = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Button22 = NULL;
lv_obj_t * ui_Button23 = NULL;
lv_obj_t * ui_Button24 = NULL;
lv_obj_t * ui_Button25 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
// event funtions
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_home1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home1_screen_init);
    }
}

void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Children1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Children1_screen_init);
    }
}

void ui_event_Button23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_chicken1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_chicken1_screen_init);
    }
}

void ui_event_Button24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InHome1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InHome1_screen_init);
    }
}

void ui_event_Button25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_seting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_seting_screen_init);
    }
}

// build funtions

void ui_seting_screen_init(void)
{
    ui_seting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_seting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_seting, &ui_img_backgraund_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_button_create(ui_seting);
    lv_obj_set_width(ui_Button8, 122);
    lv_obj_set_height(ui_Button8, 155);
    lv_obj_set_x(ui_Button8, -579);
    lv_obj_set_y(ui_Button8, -323);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button8, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button8, &ui_img_1766029311, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button22 = lv_button_create(ui_seting);
    lv_obj_set_width(ui_Button22, 122);
    lv_obj_set_height(ui_Button22, 155);
    lv_obj_set_x(ui_Button22, -579);
    lv_obj_set_y(ui_Button22, -162);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button22, &ui_img_2030772891, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button23 = lv_button_create(ui_seting);
    lv_obj_set_width(ui_Button23, 122);
    lv_obj_set_height(ui_Button23, 155);
    lv_obj_set_x(ui_Button23, -579);
    lv_obj_set_y(ui_Button23, 10);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button23, &ui_img_1962788573, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button24 = lv_button_create(ui_seting);
    lv_obj_set_width(ui_Button24, 122);
    lv_obj_set_height(ui_Button24, 155);
    lv_obj_set_x(ui_Button24, -579);
    lv_obj_set_y(ui_Button24, 178);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button24, &ui_img_86013472, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button25 = lv_button_create(ui_seting);
    lv_obj_set_width(ui_Button25, 122);
    lv_obj_set_height(ui_Button25, 132);
    lv_obj_set_x(ui_Button25, -579);
    lv_obj_set_y(ui_Button25, 333);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button25, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Button25, &ui_img_105946131, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_seting);
    lv_obj_set_width(ui_Keyboard1, 984);
    lv_obj_set_height(ui_Keyboard1, 388);
    lv_obj_set_x(ui_Keyboard1, 18);
    lv_obj_set_y(ui_Keyboard1, 186);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_TextArea1 = lv_textarea_create(ui_seting);
    lv_obj_set_width(ui_TextArea1, 970);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea1, 20);
    lv_obj_set_y(ui_TextArea1, -44);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_textarea_set_one_line(ui_TextArea1, true);

    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button24, ui_event_Button24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    uic_seting = ui_seting;

}

void ui_seting_screen_destroy(void)
{
    if(ui_seting) lv_obj_del(ui_seting);

    // NULL screen variables
    uic_seting = NULL;
    ui_seting = NULL;
    ui_Button8 = NULL;
    ui_Button22 = NULL;
    ui_Button23 = NULL;
    ui_Button24 = NULL;
    ui_Button25 = NULL;
    ui_Keyboard1 = NULL;
    ui_TextArea1 = NULL;

}
