// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: test

#ifndef UI_SETING_H
#define UI_SETING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_seting
extern void ui_seting_screen_init(void);
extern void ui_seting_screen_destroy(void);
extern lv_obj_t * ui_seting;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
extern void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
extern void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_seting;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

